INSERT INTO veicoli(nome, tipo, modello, capacita, potenza, velocita_massima, autonomia, descrizione,  posizione_attuale, disponibile, vista_banner, immagine) 
values ("NISSAN Leaf E+ N-Connecta", "autoElettrica", "berlina 3/5 porte", "62kWh", "90kW/122CV", "157km/h", "385km", "Family car 100% elettrica, per spostamenti a emissioni 0. E' dotata delle migliori tecnologie di Intelligent Driving e ti emoziona con il brivido della guida dinamica.", '{"descrizione": "STAZIONE 1 - Corso Stati Uniti 1", "latitudine": "45.0625658", "longitudine": "7.6696263"}', "true", "true", "img/autoElettrica/nissan_leaf.svg"),
("AUDI E-Tron 55 Quattro Advanced", "autoElettrica", "suv/fuoristrada", "95kWh", "158kW/215CV", "200km/h", "437km", "Il primo modello Audi completamente elettico. Perfetto anche per le lunghe percorrenze, grazie alla batteria e a un sistema intelligente di recupero dell'energia.", '{"descrizione": "STAZIONE 2 - Corso Inghilterra 47", "latitudine": "45.0754338", "longitudine": "7.6650673"}', "true", "true", "img/autoElettrica/audi_e-tron.svg"),
("FIAT 500 Hybrid Cult", "autoIbrida", "berlina 3/5 porte", "35L", "51kW/70CV", "167km/h", "745km", "La city car cabrio più famosa di sempre diventa ibrida. A bordo troverai tecnologia pensata per farti guidare con più sicurezza e goderti i momenti in viaggio.", '{"descrizione": "STAZIONE 1 - Corso Stati Uniti 1", "latitudine": "45.0625658", "longitudine": "7.6696263"}', "true", "true", "img/autoIbrida/fiat_500_hybrid.svg"),
("RENAULT Arkana Hybrid E-TECH 145", "autoIbrida", "suv/fuoristrada", "50L", "107kW/145CV", "172km/h", "1852km", "SUV ibrido che riduce i consumi di carburante fino al 40%. Ti fornisce il pieno di emozioni, tecnologie ed efficienza energetica, senza rinunciare alla sportività.", '{"descrizione": "STAZIONE 2 - Corso Inghilterra 47", "latitudine": "45.0754338", "longitudine": "7.6650673"}', "true", "true", "img/autoIbrida/renault_arkana.svg"),
("XIAOMI Mi Electric Scooter Essential", "monopattino", "ciclomotore", "5100mAh/183Wh", "500W", "20km/h", "20km", "Leggero nel look, potente nelle prestazioni. Dotato di sistema di recupero dell'energia cinetica, che aumenta ulteriormente la durata della batteria.", '{"descrizione": "STAZIONE 3 - Via Giudeppe Verdi 61", "latitudine": "45.0665578", "longitudine": "7.6972264"}', "true", "true", "img/monopattino/xiaomi_essential.svg"),
("Segway Max G30", "monopattino", "ciclomotore", "15300mAh/551Wh", "700W", "25km/h", "65km", "Offre la massima autonomia del mercato. Grazie alle migliori tecnologie, ti permette di viaggiare su tutti i terreni e percorrere facilmente anche le salite.", '{"descrizione": "STAZIONE 4 - Corso Regio Parco 12", "latitudine": "45.0753703", "longitudine": "7.6912162"}', "true", "true", "img/monopattino/segway_ninebot.svg"),
("Revoe 551691 Dirt Vtc", "bicicletta", "fatbike", "36V-10Ah", "250W", "25km/h", "40km", "Progettata per gli amanti delle avventure off-road. Funzionale, performante e capace di mantenere le sue prestazioni inalterate anche sotto stress.", '{"descrizione": "STAZIONE 3 - Via Giudeppe Verdi 61", "latitudine": "45.0665578", "longitudine": "7.6972264"}', "true", "true", "img/bicicletta/revoe_551691.svg"),
("NCM Milano Plus", "bicicletta", "urban-trekking bike", "48V-16Ah", "250W", "25km/h", "150km", "Unisce tenuta su asfalto a divertimento off-road. Dispone di un'ottima resistenza e consente di raggiungere la velocità massima, senza rallentare in salita.", '{"descrizione": "STAZIONE 4 - Corso Regio Parco 12", "latitudine": "45.0753703", "longitudine": "7.6912162"}', "true", "true", "img/bicicletta/ncm_milano_plus.svg"),
("FIAT Panda", "autoBenzina_Diesel", "1.2 Young", "37L", "51kW", "250km/h", "745km", "Non puoi dire di no alla Panda, guarda che bella macchina oh!", '{"descrizione": "STAZIONE 4 - Corso Regio Parco 12", "latitudine": "45.0753703", "longitudine": "7.6912162"}', "true", "true", "img/autoBenzina_Diesel/panda.jpg"),
("FORD Focus", "autoBenzina_Diesel", "1.0 Benzina Ecoboost", "45L", "125 CV (92 kW)", "25km/h", "40km", "Anche questa macchina nera è molto molto bellina.", '{"descrizione": "STAZIONE 3 - Via Giudeppe Verdi 61", "latitudine": "45.0665578", "longitudine": "7.6972264"}', "true", "true", "img/autoBenzina_Diesel/focus.jpg"),
("Bici", "bicicletta", "Rotta", "A piedi", "Appiedato", "5km/h", "Indefinito", "Massima efficienza nel risparmio di CO2. Andare a piedi, ma con noi non è gratis", '{"descrizione": "STAZIONE 2 - Corso Inghilterra 47", "latitudine": "45.0754338", "longitudine": "7.6650673"}', "true", "true", "img/bicicletta/bicirotta.jpg");

INSERT INTO utenti(email, password, ruolo, nome, cognome, nascita) values
("admin@admin.it", "12345", "amministratore", "Admin", "Admin", "1985-01-30"),
("ciciu@gmail.com", "pass", "utente", "Claudio", "Bisio", "1964-11-22"),
("therock@gmail.com", "dwayne", "utente", "The", "Rock", "1987-05-17"),
("ottina@gmail.com", "triste", "utente", "Isotta", "Cicietti", "1969-07-09"),
("cucchiaio@gmail.com", "noia", "utente", "Nabucco", "Donosor", "1975-12-02");

